n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
s = n1 + n2
print('A soma vale:', s)
print('A soma entre', n1 ,'e' , n2 , 'vale:', s)
print('A soma entre {} e {} vale: {}' .format(n1 , n2 , s))

n = input('Digite um valor:')
print(type(n))
n = input('Digite um valor:')
print(n.isalnum())
n = input('Digite um valor:')
print(n.isalpha()) 
n = input('Digite um valor:')
print(n.isdecimal())
n = input('Digite um valor:')
print(n.isnumeric))